# this is comment

server {
                         listen 65535 ;;   ; # commentaire
    root ./www/;
    server_name default;
    autoindex on;
    client_max_body_size 2M;

    index index.html srandria.html;

    error_page 403 errorPages/error403.html;
    error_page 404 errorPages/error404.html;
    error_page 500 errorPages/error500.html;


    location / 
    {
        methods GET;
    }

    location {
        path /upload;
        methods POST;
        client_max_body_size 0M;
        upload_dir www/uploads;
        return 301;
    }

    location /delete {
        methods DELETE;
        root ./www/uploads;
    }

    location /redirect { 
        return 301 http://localhost:8082/index.html;
    }

    location /files {
        methods GET;
        root ./www/listings;
        autoindex off;
        index files.html sandria.html;
    }

    location /cgi-mandatory {
        index index_cgi.html;
        methods GET POST;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        upload_dir ./www/cgi-mandatory/uploads
    }

    location /cgi-bonus {
        index index_cgi_bonus.html;
        methods GET;
        cgi_extension .rb;
        cgi_path /home/srandria/Documents/custom/ruby-3.4.5/ruby;
    }
}

server
{
    listen 127.0.0.1:8081;;   ;
    server_name localhost;
    return 302 /new-page;
    autoindex on;
    autoindex on;
    root ./www;
    root ./www/html;
    client_max_body_size 2M;
    upload_dir ./www/cgi-bin/uploads;

    error_page 400 /400.json;
    error_page 404 /404.html;

    index index.html srandria.html;

    location / {
        methods GET;
        index index.html;
        autoindex off;
        error_page 404 /404.html;
        error_page 403 /403.html;
        error_page 404 /404.html;
        error_page 403 /403.html;
    }
}
