# this is comment

server{
    location /{ # this is a commentaire
        methods GET POST;
        autoindex off;
    }

    location /upload{
        methods POST;
        upload_dir ./www/uploads;
    }









    location /delete{
        methods DELETE;
        root ./www/uploads;
                                            }

                location /redirect { 
        return 301 http://example.com;
    }

    location /files{           
        root ./www/files;
        autoindex on;
        index index.html;
    }

    location /cgi-bin               {
        methods GET POST;   
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        root ./www/cgi-bin;
    }

    listen 127.0.0.1:8080;server_name localhost;root ./www;
    index index.html;
    error_page 404 /404.html;
            client_max_body_size 1M;
}


server {
    listen 127.0.0.1:8081;
    server_name localhost;

    root ./www;
    index index.html;
    error_page 404 /404.html;
    client_max_body_size 1M;

    location / {
        methods GET POST;
        autoindex off;
    }

    location /upload {
        methods POST;
        upload_dir ./www/uploads;
    }

    location /delete {
        methods DELETE;
        root ./www/uploads;
    }

    location /redirect {
        return 301 http://example.com;
    }

    location /files {
        root ./www/files;
        autoindex on;
        index index.html;
    }

    location /cgi-bin {
        methods GET POST;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        root ./www/cgi-bin;
    }
}
