# this is comment

server { 
    listen 8082;
    # listen 8082; # error
    server_name localhost;
    # server_name StaffYann; # error

    root ./www;
    # root ./www/Mick; # il va ecrase le 1er valeur
    error_page 400 /400.json;
    error_page 404 /404.html;
    # error_page 404 /404.htmllllllllll; # il va ecrase le 1er valeur
    client_max_body_size 0M;
    # client_max_body_size 50M; # il va ecrase le 1er valeur

    index index.html srandria.html;
    # index index.html srandria.htmllllllllllll; # il va concatener ici
        

    location / {
        methods GET;
        index index.html;
        client_max_body_size 500000000M;
        autoindex on;
    }

    location /upload {
        methods POST;
        client_max_body_size 500000000M;
        upload_dir ./www/uploads;
    }

    location /delete {
        methods DELETE;
        root ./www/uploads;
    }

    location /redirect { 
        return 301 http://example.com;
    }

    location /files {
        root ./www/files;
        autoindex on;
        index index.html;
    }

    location /cgi-bin {
        index index_cgi.html;
        methods GET POST;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        root ./www/cgi-bin;
    }
}

